# Generated by Django 4.2.2 on 2023-07-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='ability',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='availability',
            field=models.IntegerField(default=0, verbose_name='Weapon Availability'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='close',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='concealability',
            field=models.IntegerField(default=0, verbose_name='Weapon Concealability'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Weapon Cost'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='dv',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Weapon Damage Value'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='extreme',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='far',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='medium',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='near',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='ranged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapons',
            name='rulebook',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Rulebook'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='wireless',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Weapon Name'),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='type',
            field=models.CharField(max_length=32, verbose_name='Weapon Type'),
        ),
    ]
