# Generated by Django 4.2.2 on 2023-07-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_weapons_ability_weapons_availability_weapons_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapons',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Weapon Name'),
        ),
        migrations.AddConstraint(
            model_name='weapons',
            constraint=models.UniqueConstraint(fields=('name',), name='pk_name_constraint'),
        ),
    ]
