# Generated by Django 4.2.2 on 2023-07-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_weapons_name_weapons_pk_name_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapons',
            name='id',
        ),
        migrations.AlterField(
            model_name='weapons',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Weapon Name'),
        ),
    ]
