# Generated by Django 4.2.2 on 2023-07-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_weapons_id_alter_weapons_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weapons',
            name='pk_name_constraint',
        ),
        migrations.AlterField(
            model_name='weapons',
            name='rulebook',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Rulebook Name'),
        ),
        migrations.AddConstraint(
            model_name='weapons',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name_constraint'),
        ),
        migrations.AddConstraint(
            model_name='weapons',
            constraint=models.CheckConstraint(check=models.Q(('type__isnull', False)), name='not_null_type_constraint'),
        ),
    ]
