# Generated by Django 4.2.2 on 2023-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_weapons_pk_name_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapons',
            name='availability',
            field=models.IntegerField(default=1, verbose_name='Weapon Availability'),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='concealability',
            field=models.IntegerField(default=10, verbose_name='Weapon Concealability'),
        ),
        migrations.AddConstraint(
            model_name='weapons',
            constraint=models.CheckConstraint(check=models.Q(('availability__gte', 1), ('availability__lte', 9)), name='availability_gte_1_lte_9'),
        ),
        migrations.AddConstraint(
            model_name='weapons',
            constraint=models.CheckConstraint(check=models.Q(('concealability__gte', 0), ('concealability__lte', 10)), name='concealability_gte_0_lte_10'),
        ),
        migrations.AddConstraint(
            model_name='weapons',
            constraint=models.CheckConstraint(check=models.Q(('cost__gte', 0)), name='cost_gte_0'),
        ),
    ]
