# Generated by Django 4.2.2 on 2023-07-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_weapons_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponMod',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Mod Name')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponModSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('Top', 'Top'), ('Under', 'Under'), ('Barrel', 'Barrel')], max_length=12)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weaponmod')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weapons')),
            ],
        ),
    ]
