# Generated by Django 4.2.2 on 2023-07-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_weaponmod_weaponmodslot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weapons',
            name='unique_name_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='weapons',
            name='not_null_type_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='weapons',
            name='availability_gte_1_lte_9',
        ),
        migrations.RemoveConstraint(
            model_name='weapons',
            name='concealability_gte_0_lte_10',
        ),
        migrations.RemoveConstraint(
            model_name='weapons',
            name='cost_gte_0',
        ),
        migrations.AddField(
            model_name='weaponmod',
            name='ability',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='weaponmod',
            name='availability',
            field=models.IntegerField(default=1, verbose_name='Mod Availability'),
        ),
        migrations.AddField(
            model_name='weaponmod',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Mod Cost'),
        ),
        migrations.AddField(
            model_name='weaponmod',
            name='rulebook',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Mod Rulebook Reference'),
        ),
        migrations.AddField(
            model_name='weaponmod',
            name='type',
            field=models.CharField(default='ACCESSORY', max_length=32, verbose_name='Mod Type'),
        ),
        migrations.AddField(
            model_name='weaponmod',
            name='wireless',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='rulebook',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Weapon Rulebook Reference'),
        ),
        migrations.AddConstraint(
            model_name='weaponmod',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_mod_name_constraint'),
        ),
        migrations.AddConstraint(
            model_name='weaponmod',
            constraint=models.CheckConstraint(check=models.Q(('type__isnull', False)), name='not_null_mod_type_constraint'),
        ),
        migrations.AddConstraint(
            model_name='weaponmod',
            constraint=models.CheckConstraint(check=models.Q(('availability__gte', 1), ('availability__lte', 9)), name='mod_availability_gte_1_lte_9'),
        ),
        migrations.AddConstraint(
            model_name='weaponmod',
            constraint=models.CheckConstraint(check=models.Q(('cost__gte', 0)), name='mod_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='weapons',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_weapon_name_constraint'),
        ),
        migrations.AddConstraint(
            model_name='weapons',
            constraint=models.CheckConstraint(check=models.Q(('type__isnull', False)), name='not_null_weapon_type_constraint'),
        ),
        migrations.AddConstraint(
            model_name='weapons',
            constraint=models.CheckConstraint(check=models.Q(('availability__gte', 1), ('availability__lte', 9)), name='weapon_availability_gte_1_lte_9'),
        ),
        migrations.AddConstraint(
            model_name='weapons',
            constraint=models.CheckConstraint(check=models.Q(('concealability__gte', 0), ('concealability__lte', 10)), name='weapon_concealability_gte_0_lte_10'),
        ),
        migrations.AddConstraint(
            model_name='weapons',
            constraint=models.CheckConstraint(check=models.Q(('cost__gte', 0)), name='weapon_cost_gte_0'),
        ),
    ]
