# Generated by Django 4.2.2 on 2023-07-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_weapons_unique_name_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weapons',
            name='weapon_concealability_gte_0_lte_10',
        ),
        migrations.RenameField(
            model_name='weapons',
            old_name='ability',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='weapons',
            name='concealability',
        ),
        migrations.RemoveField(
            model_name='weapons',
            name='ranged',
        ),
        migrations.AddField(
            model_name='weapons',
            name='add_rules',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='barrel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapons',
            name='dv_element',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Weapon Damage Value Element'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='legal',
            field=models.BooleanField(default=True, verbose_name='Weapon Legality Flag'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='standard_upgrades',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapons',
            name='under',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapons',
            name='weapon_ammo',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Weapon Ammo'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='weapon_mode',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Weapon Firing Options'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='weapon_skill',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Weapon Skill'),
        ),
    ]
