# Generated by Django 4.2.2 on 2023-07-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_weapons_weapon_concealability_gte_0_lte_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapons',
            name='weapon_ammo',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Weapon Ammo'),
        ),
    ]
