# Generated by Django 4.2.2 on 2023-07-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_weapons_weapon_ammo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapons',
            name='dv',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Weapon Damage Value'),
        ),
    ]
