# Generated by Django 4.2.2 on 2023-07-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_weapons_dv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualities',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Quality ID')),
                ('karma', models.IntegerField(default=0, verbose_name='Quality Karma Cost')),
                ('type', models.CharField(default='', max_length=16, verbose_name='Quality Type')),
                ('effect', models.TextField(blank=True, default='', null=True, verbose_name='Quality Game Effect')),
                ('max_level', models.IntegerField(default=1, verbose_name='Quality Maximum Level')),
                ('example', models.TextField(blank=True, default='', null=True, verbose_name='Quality Examples')),
            ],
        ),
    ]
